-- -*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/--
-- 																								--
-- Title: BD Topo data description													            --
-- Project: Urclim / Paendora (ADEME - MODEVAL 2017-5)											--
-- Abstract: This script aims to create the tables that describe the data types (from BD Topo)  --
--     and to define the corresponding values in the respective tables from the abstract model	--
--																								--
-- Author: Gwendall Petit (DECIDE Team, Lab-STICC CNRS UMR 6285)								--
-- Last update: 21/11/2019																		--
-- Licence : GPLv3 (https://www.gnu.org/licenses/gpl-3.0.html)                                  --
--																								--
-- -*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/-*/--

----------------------------------------------------------------------------------------------------------------------
-- FOR BUILDING
----------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
-- Building type, from BD Topo
--------------------------------------------------------

-- Initialize the table with all available types (NATURE in the BD Topo v2.0)
DROP TABLE IF EXISTS $BUILDING_BD_TOPO_USE_TYPE;
CREATE TABLE $BUILDING_BD_TOPO_USE_TYPE (ID_NATURE serial, NATURE varchar, TABLE_NAME varchar, ID_TYPE integer);

-- Feed the table

-- For "BATI_INDIFFERENCIE"
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(1, '', 'BATI_INDIFFERENCIE', null);
-- For "BATI_INDUSTRIEL"
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(2, 'Bâtiment agricole', 'BATI_INDUSTRIEL', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(3, 'Bâtiment commercial', 'BATI_INDUSTRIEL', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(4, 'Bâtiment industriel', 'BATI_INDUSTRIEL', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(5, 'Serre', 'BATI_INDUSTRIEL', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(6, 'Silo', 'BATI_INDUSTRIEL', null);
-- For "BATI_REMARQUABLE"
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(7, 'Aérogare', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(8, 'Arc de triomphe', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(9, 'Arène ou théâtre antique', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(10, 'Bâtiment religieux divers', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(11, 'Bâtiment sportif', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(12, 'Chapelle', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(13, 'Château', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(14, 'Eglise', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(15, 'Fort, blockhaus, casemate', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(16, 'Gare', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(17, 'Mairie', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(18, 'Monument', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(19, 'Péage', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(20, 'Préfecture', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(21, 'Sous-préfecture', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(22, 'Tour, donjon, moulin', 'BATI_REMARQUABLE', null);
INSERT INTO $BUILDING_BD_TOPO_USE_TYPE VALUES(23, 'Tribune', 'BATI_REMARQUABLE', null);

-- Define the correspondences between the BD Topo and the abstract table "$BUILDING_ABSTRACT_USE_TYPE"

-- For "BATI_INDIFFERENCIE"
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='building') WHERE NATURE ='';
-- For "BATI_INDUSTRIEL"
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='farm_auxiliary') WHERE NATURE ='Bâtiment agricole';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='commercial') WHERE NATURE ='Bâtiment commercial';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='light_industry') WHERE NATURE ='Bâtiment industriel';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='greenhouse') WHERE NATURE ='Serre';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='silo') WHERE NATURE ='Silo';
-- For "BATI_REMARQUABLE"
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='terminal') WHERE NATURE ='Aérogare';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='monument') WHERE NATURE ='Arc de triomphe';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='monument') WHERE NATURE ='Arène ou théâtre antique';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='religious') WHERE NATURE ='Bâtiment religieux divers';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='sports_centre') WHERE NATURE ='Bâtiment sportif';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='chapel') WHERE NATURE ='Chapelle';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='castle') WHERE NATURE ='Château';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='church') WHERE NATURE ='Eglise';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='military') WHERE NATURE ='Fort, blockhaus, casemate';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='train_station') WHERE NATURE ='Gare';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='townhall') WHERE NATURE ='Mairie';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='monument') WHERE NATURE ='Monument';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='toll_booth') WHERE NATURE ='Péage';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='government') WHERE NATURE ='Préfecture';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='government') WHERE NATURE ='Sous-préfecture';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='historic') WHERE NATURE ='Tour, donjon, moulin';
UPDATE $BUILDING_BD_TOPO_USE_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $BUILDING_ABSTRACT_USE_TYPE b WHERE b.TERM='grandstand') WHERE NATURE ='Tribune';


----------------------------------------------------------------------------------------------------------------------
-- FOR ROAD
----------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
-- Road type, from BD Topo
--------------------------------------------------------

-- Initialize the table with all available types (NATURE in the BD Topo v2.0)
DROP TABLE IF EXISTS $ROAD_BD_TOPO_TYPE;
CREATE TABLE $ROAD_BD_TOPO_TYPE (ID_NATURE serial, NATURE varchar, TABLE_NAME varchar, ID_TYPE integer);

-- Feed the table

INSERT INTO $ROAD_BD_TOPO_TYPE VALUES(1, 'Autoroute', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_TYPE VALUES(2, 'Quasi-autoroute', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_TYPE VALUES(3, 'Bretelle', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_TYPE VALUES(4, 'Route à 2 chaussées', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_TYPE VALUES(5, 'Route à 1 chaussée', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_TYPE VALUES(6, 'Route empierrée', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_TYPE VALUES(7, 'Chemin', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_TYPE VALUES(8, 'Bac auto', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_TYPE VALUES(9, 'Bac piéton', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_TYPE VALUES(10, 'Piste cyclable', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_TYPE VALUES(11, 'Sentier', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_TYPE VALUES(12, 'Escalier', 'ROUTE', null);

-- Define the correspondences between the BD Topo and the abstract table "$ROAD_ABSTRACT_TYPE"

UPDATE $ROAD_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $ROAD_ABSTRACT_TYPE b WHERE b.TERM='motorway') WHERE NATURE ='Autoroute';
UPDATE $ROAD_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $ROAD_ABSTRACT_TYPE b WHERE b.TERM='trunk') WHERE NATURE ='Quasi-autoroute';
UPDATE $ROAD_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $ROAD_ABSTRACT_TYPE b WHERE b.TERM='highway_link') WHERE NATURE ='Bretelle';
UPDATE $ROAD_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $ROAD_ABSTRACT_TYPE b WHERE b.TERM='primary') WHERE NATURE ='Route à 2 chaussées';
UPDATE $ROAD_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $ROAD_ABSTRACT_TYPE b WHERE b.TERM='unclassified') WHERE NATURE ='Route à 1 chaussée';
UPDATE $ROAD_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $ROAD_ABSTRACT_TYPE b WHERE b.TERM='track') WHERE NATURE ='Route empierrée';
UPDATE $ROAD_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $ROAD_ABSTRACT_TYPE b WHERE b.TERM='track') WHERE NATURE ='Chemin';
UPDATE $ROAD_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $ROAD_ABSTRACT_TYPE b WHERE b.TERM='ferry') WHERE NATURE ='Bac auto';
UPDATE $ROAD_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $ROAD_ABSTRACT_TYPE b WHERE b.TERM='ferry') WHERE NATURE ='Bac piéton';
UPDATE $ROAD_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $ROAD_ABSTRACT_TYPE b WHERE b.TERM='cycleway') WHERE NATURE ='Piste cyclable';
UPDATE $ROAD_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $ROAD_ABSTRACT_TYPE b WHERE b.TERM='path') WHERE NATURE ='Sentier';
UPDATE $ROAD_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $ROAD_ABSTRACT_TYPE b WHERE b.TERM='steps') WHERE NATURE ='Escalier';


--------------------------------------------------------
-- Road crossing, from BD Topo
--------------------------------------------------------

-- Initialize the table with all available CROSSING (FRANCHISST in the BD Topo v2.0)
DROP TABLE IF EXISTS $ROAD_BD_TOPO_CROSSING;
CREATE TABLE $ROAD_BD_TOPO_CROSSING (ID_FRANCHISST serial, FRANCHISST varchar, TABLE_NAME varchar, ID_CROSSING integer);

-- Feed the table

INSERT INTO $ROAD_BD_TOPO_CROSSING VALUES(1, 'Gué ou radier', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_CROSSING VALUES(2, 'Pont', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_CROSSING VALUES(3, 'Tunnel', 'ROUTE', null);
INSERT INTO $ROAD_BD_TOPO_CROSSING VALUES(4, 'NC', 'ROUTE', null);

-- Define the correspondences between the BD Topo and the abstract table "$ROAD_ABSTRACT_CROSSING"

UPDATE $ROAD_BD_TOPO_CROSSING SET ID_CROSSING=(SELECT b.ID_CROSSING FROM $ROAD_ABSTRACT_CROSSING b WHERE b.TERM='null') WHERE FRANCHISST ='Gué ou radier';
UPDATE $ROAD_BD_TOPO_CROSSING SET ID_CROSSING=(SELECT b.ID_CROSSING FROM $ROAD_ABSTRACT_CROSSING b WHERE b.TERM='bridge') WHERE FRANCHISST ='Pont';
UPDATE $ROAD_BD_TOPO_CROSSING SET ID_CROSSING=(SELECT b.ID_CROSSING FROM $ROAD_ABSTRACT_CROSSING b WHERE b.TERM='tunnel') WHERE FRANCHISST ='Tunnel';
UPDATE $ROAD_BD_TOPO_CROSSING SET ID_CROSSING=(SELECT b.ID_CROSSING FROM $ROAD_ABSTRACT_CROSSING b WHERE b.TERM='null') WHERE FRANCHISST ='NC';


----------------------------------------------------------------------------------------------------------------------
-- FOR RAIL
----------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
-- Rail type, from BD Topo
--------------------------------------------------------

-- Initialize the table with all available types (NATURE in the BD Topo v2.0)
DROP TABLE IF EXISTS $RAIL_BD_TOPO_TYPE;
CREATE TABLE $RAIL_BD_TOPO_TYPE (ID_NATURE serial, NATURE varchar, TABLE_NAME varchar, ID_TYPE integer);

-- Feed the table

INSERT INTO $RAIL_BD_TOPO_TYPE VALUES(1, 'LGV', 'TRONCON_VOIE_FERREE', null);
INSERT INTO $RAIL_BD_TOPO_TYPE VALUES(2, 'Principale', 'TRONCON_VOIE_FERREE', null);
INSERT INTO $RAIL_BD_TOPO_TYPE VALUES(3, 'Voie de service', 'TRONCON_VOIE_FERREE', null);
INSERT INTO $RAIL_BD_TOPO_TYPE VALUES(4, 'Voie non exploitée', 'TRONCON_VOIE_FERREE', null);
INSERT INTO $RAIL_BD_TOPO_TYPE VALUES(5, 'Transport urbain', 'TRONCON_VOIE_FERREE', null);
INSERT INTO $RAIL_BD_TOPO_TYPE VALUES(6, 'Funiculaire ou crémaillère', 'TRONCON_VOIE_FERREE', null);
INSERT INTO $RAIL_BD_TOPO_TYPE VALUES(7, 'Metro', 'TRONCON_VOIE_FERREE', null);
INSERT INTO $RAIL_BD_TOPO_TYPE VALUES(8, 'Tramway', 'TRONCON_VOIE_FERREE', null);

-- Define the correspondences between the BD Topo and the abstract table "$RAIL_ABSTRACT_TYPE"

UPDATE $RAIL_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $RAIL_ABSTRACT_TYPE b WHERE b.TERM='highspeed') WHERE NATURE ='LGV';
UPDATE $RAIL_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $RAIL_ABSTRACT_TYPE b WHERE b.TERM='rail') WHERE NATURE ='Principale';
UPDATE $RAIL_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $RAIL_ABSTRACT_TYPE b WHERE b.TERM='service_track') WHERE NATURE ='Voie de service';
UPDATE $RAIL_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $RAIL_ABSTRACT_TYPE b WHERE b.TERM='disused') WHERE NATURE ='Voie non exploitée';
UPDATE $RAIL_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $RAIL_ABSTRACT_TYPE b WHERE b.TERM='tram') WHERE NATURE ='Transport urbain';
UPDATE $RAIL_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $RAIL_ABSTRACT_TYPE b WHERE b.TERM='funicular') WHERE NATURE ='Funiculaire ou crémaillère';
UPDATE $RAIL_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $RAIL_ABSTRACT_TYPE b WHERE b.TERM='subway') WHERE NATURE ='Metro';
UPDATE $RAIL_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $RAIL_ABSTRACT_TYPE b WHERE b.TERM='tram') WHERE NATURE ='Tramway';


--------------------------------------------------------
-- Rail crossing, from BD Topo
--------------------------------------------------------

-- Initialize the table with all available CROSSING (FRANCHISST in the BD Topo v2.0)
DROP TABLE IF EXISTS $RAIL_BD_TOPO_CROSSING;
CREATE TABLE $RAIL_BD_TOPO_CROSSING (ID_FRANCHISST serial, FRANCHISST varchar, TABLE_NAME varchar, ID_CROSSING integer);

-- Feed the table

INSERT INTO $RAIL_BD_TOPO_CROSSING VALUES(1, 'Pont', 'TRONCON_VOIE_FERREE', null);
INSERT INTO $RAIL_BD_TOPO_CROSSING VALUES(2, 'Tunnel', 'TRONCON_VOIE_FERREE', null);
INSERT INTO $RAIL_BD_TOPO_CROSSING VALUES(3, 'NC', 'TRONCON_VOIE_FERREE', null);

-- Define the correspondences between the BD Topo and the abstract table "$RAIL_ABSTRACT_CROSSING"

UPDATE $RAIL_BD_TOPO_CROSSING SET ID_CROSSING=(SELECT b.ID_CROSSING FROM $RAIL_ABSTRACT_CROSSING b WHERE b.TERM='bridge') WHERE FRANCHISST ='Pont';
UPDATE $RAIL_BD_TOPO_CROSSING SET ID_CROSSING=(SELECT b.ID_CROSSING FROM $RAIL_ABSTRACT_CROSSING b WHERE b.TERM='tunnel') WHERE FRANCHISST ='Tunnel';
UPDATE $RAIL_BD_TOPO_CROSSING SET ID_CROSSING=(SELECT b.ID_CROSSING FROM $RAIL_ABSTRACT_CROSSING b WHERE b.TERM='null') WHERE FRANCHISST ='NC';


----------------------------------------------------------------------------------------------------------------------
-- FOR VEGETATION
----------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
-- Vegetation type, from BD Topo
--------------------------------------------------------

-- Initialize the table with all available types (NATURE in the BD Topo v2.0)
DROP TABLE IF EXISTS $VEGET_BD_TOPO_TYPE;
CREATE TABLE $VEGET_BD_TOPO_TYPE (ID_NATURE serial, NATURE varchar, TABLE_NAME varchar, ID_TYPE integer);

-- Feed the table

INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(1, 'Zone arborée', 'ZONE_VEGETATION', null);
INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(2, 'Forêt fermée de feuillus', 'ZONE_VEGETATION', null);
INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(3, 'Forêt fermée mixte', 'ZONE_VEGETATION', null);
INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(4, 'Forêt fermée de conifères', 'ZONE_VEGETATION', null);
INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(5, 'Forêt ouverte', 'ZONE_VEGETATION', null);
INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(6, 'Peupleraie', 'ZONE_VEGETATION', null);
INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(7, 'Haie', 'ZONE_VEGETATION', null);
INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(8, 'Lande ligneuse', 'ZONE_VEGETATION', null);
INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(9, 'Verger', 'ZONE_VEGETATION', null);
INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(10, 'Vigne', 'ZONE_VEGETATION', null);
INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(11, 'Bois', 'ZONE_VEGETATION', null);
INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(12, 'Bananeraie', 'ZONE_VEGETATION', null);
INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(13, 'Mangrove', 'ZONE_VEGETATION', null);
INSERT INTO $VEGET_BD_TOPO_TYPE VALUES(14, 'Canne à sucre', 'ZONE_VEGETATION', null);


-- Define the correspondences between the BD Topo and the abstract table "$VEGET_ABSTRACT_TYPE"

UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='wood') WHERE NATURE ='Zone arborée';
UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='forest') WHERE NATURE ='Forêt fermée de feuillus';
UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='forest') WHERE NATURE ='Forêt fermée mixte';
UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='forest') WHERE NATURE ='Forêt fermée de conifères';
UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='forest') WHERE NATURE ='Forêt ouverte';
UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='forest') WHERE NATURE ='Peupleraie';
UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='hedge') WHERE NATURE ='Haie';
UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='heath') WHERE NATURE ='Lande ligneuse';
UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='orchard') WHERE NATURE ='Verger';
UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='vineyard') WHERE NATURE ='Vigne';
UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='forest') WHERE NATURE ='Bois';
UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='banana_plants') WHERE NATURE ='Bananeraie';
UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='mangrove') WHERE NATURE ='Mangrove';
UPDATE $VEGET_BD_TOPO_TYPE SET ID_TYPE=(SELECT b.ID_TYPE FROM $VEGET_ABSTRACT_TYPE b WHERE b.TERM='sugar_cane') WHERE NATURE ='Canne à sucre';