name: CI build

on:
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: [ "CI release" ]
    branches: [ master ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    # Main build job used to
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_USER: orbisgis
          POSTGRES_PASSWORD: orbisgis
          POSTGRES_DB: orbisgis_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      # Checkout the source code of the project
      - name: Checkout
        uses: actions/checkout@v4

      # Setup the jdk using version 11 of Adoptium Temurin
      - name: Setup java 11 using Adoptium Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # Build the project using
      #   - clean : clean up the workspace
      #   - verify : perform different check like the dependency and plugin version update
      #   - package : bundle the project into pom or jar.
      - name: Build
        run: mvn clean validate compile test
